# Generated by Django 3.2.2 on 2021-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NazwaGry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytyl', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='data dodania')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gry.nazwagry')),
            ],
        ),
    ]
