# Generated by Django 3.2.2 on 2021-05-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gry', '0009_auto_20210529_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nazwagry',
            name='Dostepnosc',
        ),
    ]
