# Generated by Django 3.2.4 on 2021-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gry', '0010_remove_nazwagry_dostepnosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazwagry',
            name='DostepnySklep',
            field=models.BooleanField(default=True),
        ),
    ]
