# Generated by Django 3.2.4 on 2021-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gry', '0011_nazwagry_dostepnysklep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nazwagry',
            name='DostepnySklep',
            field=models.BooleanField(default=False),
        ),
    ]
