# Generated by Django 3.2.4 on 2021-06-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gry', '0012_alter_nazwagry_dostepnysklep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nazwagry',
            options={'ordering': ['Tytul'], 'verbose_name_plural': 'Nazwy Gier'},
        ),
    ]
